# Generated by Django 3.0.5 on 2020-05-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0002_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='defaul.jpg', upload_to='profile_pics'),
        ),
    ]
